### ISSUE TITLE
Versão no npm

### ISSUE THREAD

**Issue by AdrianoMoura** [matheuslugon/pluralize-ptbr#3]
A versão do NPM parece estar desatualizada em relação a que está aqui no GitHub, quando baixado por lá a versão que ele traz é uma antiga que não pluralizava múltiplas palavras

**Comment by majoal0** [comment]
Ola Adriano, obrigado pelo report! Assim que eu publicar a versao atualizada, eu fecho esta issue!

**Comment by majoal0** [comment]
New version is available at NPM `1.0.4`
