### ISSUE TITLE
Terminado em é

### ISSUE THREAD

**Issue by poetawd** [matheuslugon/pluralize-ptbr#4]
A palavra jacaré não está sendo pluralizada... Deve ser por causa da acentuação....

Parabéns pelo script.... Já estava começando a estudar as regras do português para fazer isto ! Muito bom mesmo ! Obrigado

**Comment by majoal0** [comment]
Olá, tudo bem? Analisarei a questão e adicionarei a regra ao dicionário.

Fique a vontade para sugestões e pull requests.
